export const bookName = {
  'cht_en' : {
    'Gen': '創',
    'Ex': '出',
    'Lev': '利',
    'Num': '民',
    'Deut': '申',
    'Josh': '書',
    'Judg': '士',
    'Ruth': '得',
    '1Sam': '撒上',
    '2Sam': '撒下',
    '1Kin': '王上',
    '2Kin': '王下',
    '1Chr': '代上',
    '2Chr': '代下',
    'Ezr': '拉',
    'Neh': '尼',
    'Esth': '斯',
    'Job': '伯',
    'Ps': '詩',
    'Prov': '箴',
    'Eccl': '傳',
    'Song': '歌',
    'Is': '賽',
    'Jer': '耶',
    'Lam': '哀',
    'Ezek': '結',
    'Dan': '但',
    'Hos': '何',
    'Joel': '珥',
    'Amos': '摩',
    'Obad': '俄',
    'Jon': '拿',
    'Mic': '彌',
    'Nah': '鴻',
    'Hab': '哈',
    'Zeph': '番',
    'Hag': '該',
    'Zech': '亞',
    'Mal': '瑪',
    'Matt': '太',
    'Mark': '可',
    'Luke': '路',
    'John': '約',
    'Acts': '徒',
    'Rom': '羅',
    '1Cor': '哥前',
    '2Cor': '哥後',
    'Gal': '加',
    'Eph': '弗',
    'Phil': '腓',
    'Col': '西',
    '1Thess': '帖前',
    '2Thess': '帖後',
    '1Tim': '提前',
    '2Tim': '提後',
    'Titus': '多',
    'Philem': '門',
    'Heb': '來',
    'James': '雅',
    '1Pet': '彼前',
    '2Pet': '彼後',
    '1John': '約壹',
    '2John': '約貳',
    '3John': '約參',
    'Jude': '猶',
    'Rev': '啟',
  },
  'cht' : {
    'Gen': '創',
    'Ex': '出',
    'Lev': '利',
    'Num': '民',
    'Deut': '申',
    'Josh': '書',
    'Judg': '士',
    'Ruth': '得',
    '1Sam': '撒上',
    '2Sam': '撒下',
    '1Kin': '王上',
    '2Kin': '王下',
    '1Chr': '代上',
    '2Chr': '代下',
    'Ezr': '拉',
    'Neh': '尼',
    'Esth': '斯',
    'Job': '伯',
    'Ps': '詩',
    'Prov': '箴',
    'Eccl': '傳',
    'Song': '歌',
    'Is': '賽',
    'Jer': '耶',
    'Lam': '哀',
    'Ezek': '結',
    'Dan': '但',
    'Hos': '何',
    'Joel': '珥',
    'Amos': '摩',
    'Obad': '俄',
    'Jon': '拿',
    'Mic': '彌',
    'Nah': '鴻',
    'Hab': '哈',
    'Zeph': '番',
    'Hag': '該',
    'Zech': '亞',
    'Mal': '瑪',
    'Matt': '太',
    'Mark': '可',
    'Luke': '路',
    'John': '約',
    'Acts': '徒',
    'Rom': '羅',
    '1Cor': '哥前',
    '2Cor': '哥後',
    'Gal': '加',
    'Eph': '弗',
    'Phil': '腓',
    'Col': '西',
    '1Thess': '帖前',
    '2Thess': '帖後',
    '1Tim': '提前',
    '2Tim': '提後',
    'Titus': '多',
    'Philem': '門',
    'Heb': '來',
    'James': '雅',
    '1Pet': '彼前',
    '2Pet': '彼後',
    '1John': '約壹',
    '2John': '約貳',
    '3John': '約參',
    'Jude': '猶',
    'Rev': '啟',
  },
  'en' : {
    'Gen': 'Gen',
    'Ex': 'Ex',
    'Lev': 'Lev',
    'Num': 'Num',
    'Deut': 'Deu',
    'Josh': 'Jos',
    'Judg': 'Jdg',
    'Ruth': 'Rth',
    '1Sam': '1Sa',
    '2Sam': '2Sa',
    '1Kin': '1Ki',
    '2Kin': '2Ki',
    '1Chr': '1Ch',
    '2Chr': '2Ch',
    'Ezr': 'Ezr',
    'Neh': 'Neh',
    'Esth': 'Est',
    'Job': 'Job',
    'Ps': 'Psa',
    'Prov': 'Pro',
    'Eccl': 'Ecc',
    'Song': 'Son',
    'Is': 'Isa',
    'Jer': 'Jer',
    'Lam': 'Lam',
    'Ezek': 'Eze',
    'Dan': 'Dan',
    'Hos': 'Hos',
    'Joel': 'Joe',
    'Amos': 'Amo',
    'Obad': 'Oba',
    'Jon': 'Jon',
    'Mic': 'Mic',
    'Nah': 'Nah',
    'Hab': 'Hab',
    'Zeph': 'Zep',
    'Hag': 'Hag',
    'Zech': 'Zec',
    'Mal': 'Mal',
    'Matt': 'Mat',
    'Mark': 'Mar',
    'Luke': 'Luk',
    'John': 'Joh',
    'Acts': 'Act',
    'Rom': 'Rom',
    '1Cor': '1Co',
    '2Cor': '2Co',
    'Gal': 'Gal',
    'Eph': 'Eph',
    'Phil': 'Php',
    'Col': 'Col',
    '1Thess': '1Th',
    '2Thess': '2Th',
    '1Tim': '1Ti',
    '2Tim': '2Ti',
    'Tit': 'Tit',
    'Philem': 'Phm',
    'Heb': 'Heb',
    'James': 'Jas',
    '1Pet': '1Pe',
    '2Pet': '2Pe',
    '1John': '1Jn',
    '2John': '2Jn',
    '3John': '3Jn',
    'Jude': 'Jud',
    'Rev': 'Rev',
  },
  'ja' : {
    'Gen': 'Gen',
    'Ex': 'Ex',
    'Lev': 'Lev',
    'Num': 'Num',
    'Deut': 'Deu',
    'Josh': 'Jos',
    'Judg': 'Jdg',
    'Ruth': 'Rth',
    '1Sam': '1Sa',
    '2Sam': '2Sa',
    '1Kin': '1Ki',
    '2Kin': '2Ki',
    '1Chr': '1Ch',
    '2Chr': '2Ch',
    'Ezr': 'Ezr',
    'Neh': 'Neh',
    'Esth': 'Est',
    'Job': 'Job',
    'Ps': 'Psa',
    'Prov': 'Pro',
    'Eccl': 'Ecc',
    'Song': 'Son',
    'Is': 'Isa',
    'Jer': 'Jer',
    'Lam': 'Lam',
    'Ezek': 'Eze',
    'Dan': 'Dan',
    'Hos': 'Hos',
    'Joel': 'Joe',
    'Amos': 'Amo',
    'Obad': 'Oba',
    'Jon': 'Jon',
    'Mic': 'Mic',
    'Nah': 'Nah',
    'Hab': 'Hab',
    'Zeph': 'Zep',
    'Hag': 'Hag',
    'Zech': 'Zec',
    'Mal': 'Mal',
    'Matt': 'Mat',
    'Mark': 'Mar',
    'Luke': 'Luk',
    'John': 'Joh',
    'Acts': 'Act',
    'Rom': 'Rom',
    '1Cor': '1Co',
    '2Cor': '2Co',
    'Gal': 'Gal',
    'Eph': 'Eph',
    'Phil': 'Php',
    'Col': 'Col',
    '1Thess': '1Th',
    '2Thess': '2Th',
    '1Tim': '1Ti',
    '2Tim': '2Ti',
    'Tit': 'Tit',
    'Philem': 'Phm',
    'Heb': 'Heb',
    'James': 'Jas',
    '1Pet': '1Pe',
    '2Pet': '2Pe',
    '1John': '1Jn',
    '2John': '2Jn',
    '3John': '3Jn',
    'Jude': 'Jud',
    'Rev': 'Rev',
  },
  'chs' : {
    'Gen': '创',
    'Ex': '出',
    'Lev': '利',
    'Num': '民',
    'Deut': '申',
    'Josh': '书',
    'Judg': '士',
    'Ruth': '得',
    '1Sam': '撒上',
    '2Sam': '撒下',
    '1Kin': '王上',
    '2Kin': '王下',
    '1Chr': '代上',
    '2Chr': '代下',
    'Ezr': '拉',
    'Neh': '尼',
    'Esth': '斯',
    'Job': '伯',
    'Ps': '诗',
    'Prov': '箴',
    'Eccl': '传',
    'Song': '歌',
    'Is': '賽',
    'Jer': '耶',
    'Lam': '哀',
    'Ezek': '結',
    'Dan': '但',
    'Hos': '何',
    'Joel': '珥',
    'Amos': '摩',
    'Obad': '俄',
    'Jon': '拿',
    'Mic': '弥',
    'Nah': '鴻',
    'Hab': '哈',
    'Zeph': '番',
    'Hag': '该',
    'Zech': '亚',
    'Mal': '玛',
    'Matt': '太',
    'Mark': '可',
    'Luke': '路',
    'John': '約',
    'Acts': '徒',
    'Rom': '罗',
    '1Cor': '哥前',
    '2Cor': '哥後',
    'Gal': '加',
    'Eph': '弗',
    'Phil': '腓',
    'Col': '西',
    '1Thess': '帖前',
    '2Thess': '帖後',
    '1Tim': '提前',
    '2Tim': '提後',
    'Titus': '多',
    'Philem': '門',
    'Heb': '来',
    'James': '雅',
    '1Pet': '彼前',
    '2Pet': '彼後',
    '1John': '约壹',
    '2John': '约贰',
    '3John': '约参',
    'Jude': '犹',
    'Rev': '启',
  }
}



// export const bookName = {
//   'cht' : {
//     'Gen-': '創',
//     'Genesis': '創世紀',
//     'Ex-': '出',
//     'Exodus': '出埃及記',
//     'Lev-': '利',
//     'Leviticus': '利未記',
//     'Num-': '民',
//     'Numbers': '民數紀',
//     'Deut-': '申',
//     'Deuteronomy': '申命記',
//     'Josh-': '書',
//     'Joshua': '約書亞紀',
//     'Judg-': '士',
//     'Judges': '士師記',
//     'Ruth-': '得',
//     'Ruth': '路得記',
//     '1Sam-': '撒上',
//     '1Samuel': '撒母耳記上',
//     '2Sam-': '撒下',
//     '2Samuel': '撒母耳記下',
//     '1Kin-': '王上',
//     '1Kings': '列王紀上',
//     '2Kin-': '王下',
//     '2Kings': '列王紀下',
//     '1Chr-': '代上',
//     '1Chronicles': '歷代志上',
//     '2Chr-': '代下',
//     '2Chronicles': '歷代志下',
//     'Ezr-': '拉',
//     'Ezra': '以斯拉記',
//     'Neh-': '尼',
//     'Nehemiah': '尼希米記',
//     'Esth-': '斯',
//     'Esther': '以斯帖記',
//     'Job-': '伯',
//     'Job': '約伯記',
//     'Ps-': '詩',
//     'Psalms': '詩篇',
//     'Prov-': '箴',
//     'Proverbs': '箴言',
//     'Eccl': '傳',
//     'Ecclesiastes': '傳道書',
//     'Song-': '歌',
//     'Song of Solomon': '雅歌',
//     'Is-': '賽',
//     'Isaiah': '以賽亞書',
//     'Jer-': '耶',
//     'Jeremiah': '耶利米書',
//     'Lam-': '哀',
//     'Lamentations': '耶利米哀歌',
//     'Ezek-': '結',
//     'Ezekiel': '以西結書',
//     'Dan-': '但',
//     'Daniel': '但以理書',
//     'Hos-': '何',
//     'Hosea': '何西阿書',
//     'Joel-': '珥',
//     'Joel': '約珥書',
//     'Amos-': '摩',
//     'Amos': '阿摩司書',
//     'Obad-': '俄',
//     'Obadiah': '俄巴底亞書',
//     'Jon-': '拿',
//     'Jonah': '約拿書',
//     'Mic-': '彌',
//     'Micah': '彌迦書',
//     'Nah-': '鴻',
//     'Nahum': '那鴻書',
//     'Hab-': '哈',
//     'Habakkuk': '哈巴谷書',
//     'Zeph-': '番',
//     'Zephaniah': '西番雅書',
//     'Hag-': '該',
//     'Haggai': '哈該書',
//     'Zech-': '亞',
//     'Zechariah': '撒迦利亞書',
//     'Mal-': '瑪',
//     'Malachi': '瑪拉基書',
//     'Matt-': '太',
//     'Matthew': '馬太福音',
//     'Mark-': '可',
//     'Mark': '馬可福音',
//     'Luke-': '路',
//     'Luke': '路加福音',
//     'John-': '約',
//     'John': '約翰福音',
//     'Acts-': '徒',
//     'Acts': '使徒行傳',
//     'Rom-': '羅',
//     'Romans': '羅馬書',
//     '1Cor-': '哥前',
//     '1Corinthians': '哥林多前書',
//     '2Cor-': '哥後',
//     '2Corinthians': '哥林多後書',
//     'Gal-': '加',
//     'Galatians': '加拉太書',
//     'Eph-': '弗',
//     'Ephesians': '以弗所書',
//     'Phil-': '腓',
//     'Philippians': '腓立比書',
//     'Col-': '西',
//     'Colossians': '歌羅西書',
//     '1Thess-': '帖前',
//     '1Thessalonians': '帖撒羅尼迦前書',
//     '2Thess-': '帖後',
//     '2Thessalonians': '帖撒羅尼迦後書',
//     '1Tim-': '提前',
//     '1Timothy': '提摩太前書',
//     '2Tim-': '提後',
//     '2Timothy': '提摩太後書',
//     'Titus-': '多',
//     'Titus': '提多書',
//     'Philem-': '門',
//     'Philemon': '腓利門書',
//     'Heb-': '來',
//     'Hebrews': '希伯來書',
//     'James-': '雅',
//     'James': '雅各書',
//     '1Pet-': '彼前',
//     '1Peter': '彼得前書',
//     '2Pet-': '彼後',
//     '2Peter': '彼得後書',
//     '1John-': '約壹',
//     '1John': '約翰一書',
//     '2John-': '約貳',
//     '2John': '約翰二書',
//     '3John-': '約參',
//     '3John': '約翰三書',
//     'Jude-': '猶',
//     'Jude': '猶大書',
//     'Rev-': '啟',
//     'Revelation': '啟示錄',
//   },
//   'en' : {
//     'Gen-': 'Gen',
//     'Genesis': 'Genesis',
//     'Ex-': 'Ex',
//     'Exodus': 'Exodus',
//     'Lev-': 'Lev',
//     'Leviticus': 'Leviticus',
//     'Num-': 'Num',
//     'Numbers': 'Numbers',
//     'Deut-': 'Deut',
//     'Deuteronomy': 'Deuteronomy',
//     'Josh-': 'Josh',
//     'Joshua': 'Joshua',
//     'Judg-': 'Judg',
//     'Judges': 'Judges',
//     'Ruth-': 'Ruth',
//     'Ruth': 'Ruth',
//     '1Sam-': '1Sam',
//     '1Samuel': '1Samuel',
//     '2Sam-': '2Sam',
//     '2Samuel': '2Samuel',
//     '1Kin-': '1Kin',
//     '1Kings': '1Kings',
//     '2Kin-': '2Kin',
//     '2Kings': '2Kings',
//     '1Chr-': '1Chr',
//     '1Chronicles': '1Chronicles',
//     '2Chr-': '2Chr',
//     '2Chronicles': '2Chronicles',
//     'Ezr-': 'Ezr',
//     'Ezra': 'Ezra',
//     'Neh-': 'Neh',
//     'Nehemiah': 'Nehemiah',
//     'Esth-': 'Esth',
//     'Esther': 'Esther',
//     'Job-': 'Job',
//     'Job': 'Job',
//     'Ps-': 'Ps',
//     'Psalms': 'Psalms',
//     'Prov-': 'Prov',
//     'Proverbs': 'Proverbs',
//     'Eccl': 'Eccl',
//     'Ecclesiastes': 'Ecclesiastes',
//     'Song-': 'Song',
//     'Song of Solomon': 'Song of Solomon',
//     'Is-': 'Is',
//     'Isaiah': 'Isaiah',
//     'Jer-': 'Jer',
//     'Jeremiah': 'Jeremiah',
//     'Lam-': 'Lam',
//     'Lamentations': 'Lamentations',
//     'Ezek-': 'Ezek',
//     'Ezekiel': 'Ezekiel',
//     'Dan-': 'Dan',
//     'Daniel': 'Daniel',
//     'Hos-': 'Hos',
//     'Hosea': 'Hosea',
//     'Joel-': 'Joel',
//     'Joel': 'Joel',
//     'Amos-': 'Amos',
//     'Amos': 'Amos',
//     'Obad-': 'Obad',
//     'Obadiah': 'Obadiah',
//     'Jon-': 'Jon',
//     'Jonah': 'Jonah',
//     'Mic-': 'Mic',
//     'Micah': 'Micah',
//     'Nah-': 'Nah',
//     'Nahum': 'Nahum',
//     'Hab-': 'Hab',
//     'Habakkuk': 'Habakkuk',
//     'Zeph-': 'Zeph',
//     'Zephaniah': 'Zephaniah',
//     'Hag-': 'Hag',
//     'Haggai': 'Haggai',
//     'Zech-': 'Zech',
//     'Zechariah': 'Zechariah',
//     'Mal-': 'Mal',
//     'Malachi': 'Malachi',
//     'Matt-': 'Matt',
//     'Matthew': 'Matthew',
//     'Mark-': 'Mark',
//     'Mark': 'Mark',
//     'Luke-': 'Luke',
//     'Luke': 'Luke',
//     'John-': 'John',
//     'John': 'John',
//     'Acts-': 'Acts',
//     'Acts': 'Acts',
//     'Rom-': 'Rom',
//     'Romans': 'Romans',
//     '1Cor-': '1Cor',
//     '1Corinthians': '1Corinthians',
//     '2Cor-': '2Cor',
//     '2Corinthians': '2Corinthians',
//     'Gal-': 'Gal',
//     'Galatians': 'Galatians',
//     'Eph-': 'Eph',
//     'Ephesians': 'Ephesians',
//     'Phil-': 'Phil',
//     'Philippians': 'Philippians',
//     'Col-': 'Col',
//     'Colossians': 'Colossians',
//     '1Thess-': '1Thess',
//     '1Thessalonians': '1Thessalonians',
//     '2Thess-': '2Thess',
//     '2Thessalonians': '2Thessalonians',
//     '1Tim-': '1Tim',
//     '1Timothy': '1Timothy',
//     '2Tim-': '2Tim',
//     '2Timothy': '2Timothy',
//     'Titus-': 'Titus',
//     'Titus': 'Titus',
//     'Philem-': 'Philem',
//     'Philemon': 'Philemon',
//     'Heb-': 'Heb',
//     'Hebrews': 'Hebrews',
//     'James-': 'James',
//     'James': 'James',
//     '1Pet-': '1Pet',
//     '1Peter': '1Peter',
//     '2Pet-': '2Pet',
//     '2Peter': '2Peter',
//     '1John-': '1John',
//     '1John': '1John',
//     '2John-': '2John',
//     '2John': '2John',
//     '3John-': '3John',
//     '3John': '3John',
//     'Jude-': 'Jude',
//     'Jude': 'Jude',
//     'Rev-': 'Rev',
//     'Revelation': 'Revelation',
//   },
//   'chs' : {
//     'Gen-': '创',
//     'Genesis': '创世纪',
//     'Ex-': '出',
//     'Exodus': '出埃及记',
//     'Lev-': '利',
//     'Leviticus': '利未记',
//     'Num-': '民',
//     'Numbers': '民数纪',
//     'Deut-': '申',
//     'Deuteronomy': '申命记',
//     'Josh-': '书',
//     'Joshua': '约书亚纪',
//     'Judg-': '士',
//     'Judges': '士师记',
//     'Ruth-': '路得记',
//     'Ruth': '路得记',
//     '1Sam-': '撒上',
//     '1Samuel': '撒母耳記上',
//     '2Sam-': '撒下',
//     '2Samuel': '撒母耳记下',
//     '1Kin-': '王上',
//     '1Kings': '列王紀上',
//     '2Kin-': '王下',
//     '2Kings': '列王紀下',
//     '1Chr-': '代上',
//     '1Chronicles': '历代志上',
//     '2Chr-': '代下',
//     '2Chronicles': '历代志下',
//     'Ezr-': '拉',
//     'Ezra': '以斯拉记',
//     'Neh-': '尼',
//     'Nehemiah': '尼希米记',
//     'Esth-': '斯',
//     'Esther': '以斯帖记',
//     'Job-': '伯',
//     'Job': '约伯记',
//     'Ps-': '诗',
//     'Psalms': '诗篇',
//     'Prov-': '箴',
//     'Proverbs': '箴言',
//     'Eccl': '传',
//     'Ecclesiastes': '传道书',
//     'Song-': '歌',
//     'Song of Solomon': '雅歌',
//     'Is-': '賽',
//     'Isaiah': '以赛亚书',
//     'Jer-': '耶',
//     'Jeremiah': '耶利米书',
//     'Lam-': '哀',
//     'Lamentations': '耶利米哀歌',
//     'Ezek-': '結',
//     'Ezekiel': '以西结书',
//     'Dan-': '但',
//     'Daniel': '但以理书',
//     'Hos-': '何',
//     'Hosea': '何西阿书',
//     'Joel-': '珥',
//     'Joel': '约珥书',
//     'Amos-': '摩',
//     'Amos': '阿摩司书',
//     'Obad-': '俄',
//     'Obadiah': '俄巴底亚书',
//     'Jon-': '拿',
//     'Jonah': '约拿书',
//     'Mic-': '弥',
//     'Micah': '弥迦书',
//     'Nah-': '鴻',
//     'Nahum': '那鸿书',
//     'Hab-': '哈',
//     'Habakkuk': '哈巴谷书',
//     'Zeph-': '番',
//     'Zephaniah': '西番雅书',
//     'Hag-': '该',
//     'Haggai': '哈该书',
//     'Zech-': '亚',
//     'Zechariah': '撒迦利亚书',
//     'Mal-': '玛',
//     'Malachi': '玛拉基书',
//     'Matt-': '太',
//     'Matthew': '马太福音',
//     'Mark-': '可',
//     'Mark': '马可福音',
//     'Luke-': '路',
//     'Luke': '路加福音',
//     'John-': '約',
//     'John': '約翰福音',
//     'Acts-': '徒',
//     'Acts': '使徒行传',
//     'Rom-': '罗',
//     'Romans': '罗马书',
//     '1Cor-': '哥前',
//     '1Corinthians': '哥林多前书',
//     '2Cor-': '哥後',
//     '2Corinthians': '哥林多後书',
//     'Gal-': '加',
//     'Galatians': '加拉太书',
//     'Eph-': '弗',
//     'Ephesians': '以弗所书',
//     'Phil-': '腓',
//     'Philippians': '腓立比书',
//     'Col-': '西',
//     'Colossians': '歌罗西书',
//     '1Thess-': '帖前',
//     '1Thessalonians': '帖撒罗尼迦前书',
//     '2Thess-': '帖後',
//     '2Thessalonians': '帖撒罗尼迦後书',
//     '1Tim-': '提前',
//     '1Timothy': '提摩太前书',
//     '2Tim-': '提後',
//     '2Timothy': '提摩太後书',
//     'Titus-': '多',
//     'Titus': '提多书',
//     'Philem-': '門',
//     'Philemon': '腓利門书',
//     'Heb-': '来',
//     'Hebrews': '希伯来书',
//     'James-': '雅',
//     'James': '雅各书',
//     '1Pet-': '彼前',
//     '1Peter': '彼得前书',
//     '2Pet-': '彼後',
//     '2Peter': '彼得後书',
//     '1John-': '约壹',
//     '1John': '约翰一书',
//     '2John-': '约贰',
//     '2John': '约翰二书',
//     '3John-': '约参',
//     '3John': '约翰三书',
//     'Jude-': '犹',
//     'Jude': '犹大书',
//     'Rev-': '启',
//     'Revelation': '启示录',
//   }
// }